//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D3PieChartWithWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityPopulationTable
    {
        public int CityID { get; set; }
        public string CityName { get; set; }
        public Nullable<int> Population { get; set; }
    }
}
